%%
%在0<ω<2π内分析幅频特性与相频特性
dw=0.001;
w=0:dw:2*pi;
z=exp(1i*w);
A=0.5;
H=z./(z-A);
figure
subplot(1,2,1)
plot(abs(H))
title(['$$|H(e^{j\omega})|$$'],'interpreter','latex')
subplot(1,2,2)
plot(angle(H))
title(['$$Arg[H(e^{j\omega})]$$'],'interpreter','latex')
%%
%低通、高通与带通
dw=0.001;
w=0:dw:2*pi;
z=exp(1i*w);
figure
subplot(3,1,1)
A=0.5;
H=z./(z-A);
plot(abs(H))
title("Low Pass Filter")
subplot(3,1,2)
A=-0.5;
H=z./(z-A);
plot(abs(H))
title("High Pass Filter")
subplot(3,1,3)
A=0;
H=z./(z-A);
plot(abs(H))
title("All Pass Filter")
%%
%在0<ω<4π内分析周期性与对称性
dw=0.001;
w=0:dw:4*pi;
z=exp(1i*w);
A=0.5;
H=z./(z-A);
figure
subplot(1,2,1)
plot(abs(H))
title(['$$|H(e^{j\omega})|$$'],'interpreter','latex')
subplot(1,2,2)
plot(angle(H))
title(['$$Arg[H(e^{j\omega})]$$'],'interpreter','latex')